// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/21/2026, 3:00:37 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Nikita/Desktop/dvsouvenir/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/dvsouvenir/frontend/components/ui/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/dvsouvenir/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/dvsouvenir/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/dvsouvenir/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Nikita/Desktop/dvsouvenir/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Nikita/Desktop/dvsouvenir/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Nikita/Desktop/dvsouvenir/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/dvsouvenir/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/dvsouvenir/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Nikita/Desktop/dvsouvenir/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;