
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AdminBreadcrumbs': typeof import("../components/ui/AdminBreadcrumbs.vue")['default']
    'AdminButton': typeof import("../components/ui/AdminButton.vue")['default']
    'AdminCard': typeof import("../components/ui/AdminCard.vue")['default']
    'AdminInput': typeof import("../components/ui/AdminInput.vue")['default']
    'AdminPageHeader': typeof import("../components/ui/AdminPageHeader.vue")['default']
    'AdminPagination': typeof import("../components/ui/AdminPagination.vue")['default']
    'AdminSelect': typeof import("../components/ui/AdminSelect.vue")['default']
    'AdminStatusBadge': typeof import("../components/ui/AdminStatusBadge.vue")['default']
    'BaseBadge': typeof import("../components/ui/BaseBadge.vue")['default']
    'BaseButton': typeof import("../components/ui/BaseButton.vue")['default']
    'BaseInput': typeof import("../components/ui/BaseInput.vue")['default']
    'FaviconIcon': typeof import("../components/ui/FaviconIcon.vue")['default']
    'CartCrossSell': typeof import("../components/CartCrossSell.vue")['default']
    'CartSummary': typeof import("../components/CartSummary.vue")['default']
    'CatalogFiltersSidebar': typeof import("../components/CatalogFiltersSidebar.vue")['default']
    'CategoryMicroBanner': typeof import("../components/CategoryMicroBanner.vue")['default']
    'CityPicker': typeof import("../components/CityPicker.vue")['default']
    'HomeCategoriesMega': typeof import("../components/HomeCategoriesMega.vue")['default']
    'HomeCategoryProducts': typeof import("../components/HomeCategoryProducts.vue")['default']
    'HomePersonalizedProducts': typeof import("../components/HomePersonalizedProducts.vue")['default']
    'OrderCard': typeof import("../components/OrderCard.vue")['default']
    'ProductAvailabilityBadge': typeof import("../components/ProductAvailabilityBadge.vue")['default']
    'ProductCard': typeof import("../components/ProductCard.vue")['default']
    'ProductCardGrid': typeof import("../components/ProductCardGrid.vue")['default']
    'ProductCardList': typeof import("../components/ProductCardList.vue")['default']
    'ProductCardSkeleton': typeof import("../components/ProductCardSkeleton.vue")['default']
    'ProductGallery': typeof import("../components/ProductGallery.vue")['default']
    'ProductLabel': typeof import("../components/ProductLabel.vue")['default']
    'ProductPriceBlock': typeof import("../components/ProductPriceBlock.vue")['default']
    'ProductReviewsBasic': typeof import("../components/ProductReviewsBasic.vue")['default']
    'ProductRow': typeof import("../components/ProductRow.vue")['default']
    'ProductRowSkeleton': typeof import("../components/ProductRowSkeleton.vue")['default']
    'PromoCarousel': typeof import("../components/PromoCarousel.vue")['default']
    'QuickFilterChips': typeof import("../components/QuickFilterChips.vue")['default']
    'ScrollToTop': typeof import("../components/ScrollToTop.vue")['default']
    'SmartSearchBar': typeof import("../components/SmartSearchBar.vue")['default']
    'ToastHost': typeof import("../components/ToastHost.vue")['default']
    'ViewToggle': typeof import("../components/ViewToggle.vue")['default']
    'AdminNavIcon': typeof import("../components/admin/AdminNavIcon.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'VitePwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaAssets': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'PwaAppleImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'PwaAppleSplashScreenImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'PwaFaviconImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'PwaMaskableImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'PwaTransparentImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAdminBreadcrumbs': typeof import("../components/ui/AdminBreadcrumbs.vue")['default']
    'LazyAdminButton': typeof import("../components/ui/AdminButton.vue")['default']
    'LazyAdminCard': typeof import("../components/ui/AdminCard.vue")['default']
    'LazyAdminInput': typeof import("../components/ui/AdminInput.vue")['default']
    'LazyAdminPageHeader': typeof import("../components/ui/AdminPageHeader.vue")['default']
    'LazyAdminPagination': typeof import("../components/ui/AdminPagination.vue")['default']
    'LazyAdminSelect': typeof import("../components/ui/AdminSelect.vue")['default']
    'LazyAdminStatusBadge': typeof import("../components/ui/AdminStatusBadge.vue")['default']
    'LazyBaseBadge': typeof import("../components/ui/BaseBadge.vue")['default']
    'LazyBaseButton': typeof import("../components/ui/BaseButton.vue")['default']
    'LazyBaseInput': typeof import("../components/ui/BaseInput.vue")['default']
    'LazyFaviconIcon': typeof import("../components/ui/FaviconIcon.vue")['default']
    'LazyCartCrossSell': typeof import("../components/CartCrossSell.vue")['default']
    'LazyCartSummary': typeof import("../components/CartSummary.vue")['default']
    'LazyCatalogFiltersSidebar': typeof import("../components/CatalogFiltersSidebar.vue")['default']
    'LazyCategoryMicroBanner': typeof import("../components/CategoryMicroBanner.vue")['default']
    'LazyCityPicker': typeof import("../components/CityPicker.vue")['default']
    'LazyHomeCategoriesMega': typeof import("../components/HomeCategoriesMega.vue")['default']
    'LazyHomeCategoryProducts': typeof import("../components/HomeCategoryProducts.vue")['default']
    'LazyHomePersonalizedProducts': typeof import("../components/HomePersonalizedProducts.vue")['default']
    'LazyOrderCard': typeof import("../components/OrderCard.vue")['default']
    'LazyProductAvailabilityBadge': typeof import("../components/ProductAvailabilityBadge.vue")['default']
    'LazyProductCard': typeof import("../components/ProductCard.vue")['default']
    'LazyProductCardGrid': typeof import("../components/ProductCardGrid.vue")['default']
    'LazyProductCardList': typeof import("../components/ProductCardList.vue")['default']
    'LazyProductCardSkeleton': typeof import("../components/ProductCardSkeleton.vue")['default']
    'LazyProductGallery': typeof import("../components/ProductGallery.vue")['default']
    'LazyProductLabel': typeof import("../components/ProductLabel.vue")['default']
    'LazyProductPriceBlock': typeof import("../components/ProductPriceBlock.vue")['default']
    'LazyProductReviewsBasic': typeof import("../components/ProductReviewsBasic.vue")['default']
    'LazyProductRow': typeof import("../components/ProductRow.vue")['default']
    'LazyProductRowSkeleton': typeof import("../components/ProductRowSkeleton.vue")['default']
    'LazyPromoCarousel': typeof import("../components/PromoCarousel.vue")['default']
    'LazyQuickFilterChips': typeof import("../components/QuickFilterChips.vue")['default']
    'LazyScrollToTop': typeof import("../components/ScrollToTop.vue")['default']
    'LazySmartSearchBar': typeof import("../components/SmartSearchBar.vue")['default']
    'LazyToastHost': typeof import("../components/ToastHost.vue")['default']
    'LazyViewToggle': typeof import("../components/ViewToggle.vue")['default']
    'LazyAdminNavIcon': typeof import("../components/admin/AdminNavIcon.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyVitePwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaAssets': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'LazyPwaAppleImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'LazyPwaAppleSplashScreenImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'LazyPwaFaviconImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'LazyPwaMaskableImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'LazyPwaTransparentImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AdminBreadcrumbs: typeof import("../components/ui/AdminBreadcrumbs.vue")['default']
export const AdminButton: typeof import("../components/ui/AdminButton.vue")['default']
export const AdminCard: typeof import("../components/ui/AdminCard.vue")['default']
export const AdminInput: typeof import("../components/ui/AdminInput.vue")['default']
export const AdminPageHeader: typeof import("../components/ui/AdminPageHeader.vue")['default']
export const AdminPagination: typeof import("../components/ui/AdminPagination.vue")['default']
export const AdminSelect: typeof import("../components/ui/AdminSelect.vue")['default']
export const AdminStatusBadge: typeof import("../components/ui/AdminStatusBadge.vue")['default']
export const BaseBadge: typeof import("../components/ui/BaseBadge.vue")['default']
export const BaseButton: typeof import("../components/ui/BaseButton.vue")['default']
export const BaseInput: typeof import("../components/ui/BaseInput.vue")['default']
export const FaviconIcon: typeof import("../components/ui/FaviconIcon.vue")['default']
export const CartCrossSell: typeof import("../components/CartCrossSell.vue")['default']
export const CartSummary: typeof import("../components/CartSummary.vue")['default']
export const CatalogFiltersSidebar: typeof import("../components/CatalogFiltersSidebar.vue")['default']
export const CategoryMicroBanner: typeof import("../components/CategoryMicroBanner.vue")['default']
export const CityPicker: typeof import("../components/CityPicker.vue")['default']
export const HomeCategoriesMega: typeof import("../components/HomeCategoriesMega.vue")['default']
export const HomeCategoryProducts: typeof import("../components/HomeCategoryProducts.vue")['default']
export const HomePersonalizedProducts: typeof import("../components/HomePersonalizedProducts.vue")['default']
export const OrderCard: typeof import("../components/OrderCard.vue")['default']
export const ProductAvailabilityBadge: typeof import("../components/ProductAvailabilityBadge.vue")['default']
export const ProductCard: typeof import("../components/ProductCard.vue")['default']
export const ProductCardGrid: typeof import("../components/ProductCardGrid.vue")['default']
export const ProductCardList: typeof import("../components/ProductCardList.vue")['default']
export const ProductCardSkeleton: typeof import("../components/ProductCardSkeleton.vue")['default']
export const ProductGallery: typeof import("../components/ProductGallery.vue")['default']
export const ProductLabel: typeof import("../components/ProductLabel.vue")['default']
export const ProductPriceBlock: typeof import("../components/ProductPriceBlock.vue")['default']
export const ProductReviewsBasic: typeof import("../components/ProductReviewsBasic.vue")['default']
export const ProductRow: typeof import("../components/ProductRow.vue")['default']
export const ProductRowSkeleton: typeof import("../components/ProductRowSkeleton.vue")['default']
export const PromoCarousel: typeof import("../components/PromoCarousel.vue")['default']
export const QuickFilterChips: typeof import("../components/QuickFilterChips.vue")['default']
export const ScrollToTop: typeof import("../components/ScrollToTop.vue")['default']
export const SmartSearchBar: typeof import("../components/SmartSearchBar.vue")['default']
export const ToastHost: typeof import("../components/ToastHost.vue")['default']
export const ViewToggle: typeof import("../components/ViewToggle.vue")['default']
export const AdminNavIcon: typeof import("../components/admin/AdminNavIcon.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const VitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const PwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const PwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const PwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAdminBreadcrumbs: typeof import("../components/ui/AdminBreadcrumbs.vue")['default']
export const LazyAdminButton: typeof import("../components/ui/AdminButton.vue")['default']
export const LazyAdminCard: typeof import("../components/ui/AdminCard.vue")['default']
export const LazyAdminInput: typeof import("../components/ui/AdminInput.vue")['default']
export const LazyAdminPageHeader: typeof import("../components/ui/AdminPageHeader.vue")['default']
export const LazyAdminPagination: typeof import("../components/ui/AdminPagination.vue")['default']
export const LazyAdminSelect: typeof import("../components/ui/AdminSelect.vue")['default']
export const LazyAdminStatusBadge: typeof import("../components/ui/AdminStatusBadge.vue")['default']
export const LazyBaseBadge: typeof import("../components/ui/BaseBadge.vue")['default']
export const LazyBaseButton: typeof import("../components/ui/BaseButton.vue")['default']
export const LazyBaseInput: typeof import("../components/ui/BaseInput.vue")['default']
export const LazyFaviconIcon: typeof import("../components/ui/FaviconIcon.vue")['default']
export const LazyCartCrossSell: typeof import("../components/CartCrossSell.vue")['default']
export const LazyCartSummary: typeof import("../components/CartSummary.vue")['default']
export const LazyCatalogFiltersSidebar: typeof import("../components/CatalogFiltersSidebar.vue")['default']
export const LazyCategoryMicroBanner: typeof import("../components/CategoryMicroBanner.vue")['default']
export const LazyCityPicker: typeof import("../components/CityPicker.vue")['default']
export const LazyHomeCategoriesMega: typeof import("../components/HomeCategoriesMega.vue")['default']
export const LazyHomeCategoryProducts: typeof import("../components/HomeCategoryProducts.vue")['default']
export const LazyHomePersonalizedProducts: typeof import("../components/HomePersonalizedProducts.vue")['default']
export const LazyOrderCard: typeof import("../components/OrderCard.vue")['default']
export const LazyProductAvailabilityBadge: typeof import("../components/ProductAvailabilityBadge.vue")['default']
export const LazyProductCard: typeof import("../components/ProductCard.vue")['default']
export const LazyProductCardGrid: typeof import("../components/ProductCardGrid.vue")['default']
export const LazyProductCardList: typeof import("../components/ProductCardList.vue")['default']
export const LazyProductCardSkeleton: typeof import("../components/ProductCardSkeleton.vue")['default']
export const LazyProductGallery: typeof import("../components/ProductGallery.vue")['default']
export const LazyProductLabel: typeof import("../components/ProductLabel.vue")['default']
export const LazyProductPriceBlock: typeof import("../components/ProductPriceBlock.vue")['default']
export const LazyProductReviewsBasic: typeof import("../components/ProductReviewsBasic.vue")['default']
export const LazyProductRow: typeof import("../components/ProductRow.vue")['default']
export const LazyProductRowSkeleton: typeof import("../components/ProductRowSkeleton.vue")['default']
export const LazyPromoCarousel: typeof import("../components/PromoCarousel.vue")['default']
export const LazyQuickFilterChips: typeof import("../components/QuickFilterChips.vue")['default']
export const LazyScrollToTop: typeof import("../components/ScrollToTop.vue")['default']
export const LazySmartSearchBar: typeof import("../components/SmartSearchBar.vue")['default']
export const LazyToastHost: typeof import("../components/ToastHost.vue")['default']
export const LazyViewToggle: typeof import("../components/ViewToggle.vue")['default']
export const LazyAdminNavIcon: typeof import("../components/admin/AdminNavIcon.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyVitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const LazyPwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const LazyPwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const LazyPwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const LazyPwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const LazyPwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
